version: '3.9'

services:
  idempotency-api:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - memcached
      - postgres

  memcached:
    image: memcached:1.6
    ports:
      - 11211:11211
    command: [ "memcached" ]

  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=idempotency
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./sql/fill_table.sql:/docker-entrypoint-initdb.d/fill_table.sql
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 30s
      timeout: 10s
      retries: 5
